name: agmc
description: "Asgar Ali Medical College"
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.4
  websafe_svg: ^3.0.1+1
  equatable: ^2.0.5
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  get: ^4.6.6
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  flutter_pdfview: ^1.3.2
  velocity_x: ^4.1.1
  carousel_slider: ^4.2.1
  awesome_dialog: ^3.2.0
  connectivity: ^3.0.6
  share: ^2.0.4
  flutter_cached_pdfview: ^0.4.2
  super_context_menu: ^0.8.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

 
  assets:
   - assets/icons/
   - assets/images/
   - assets/Backgrounds/

fonts:
  - family: Muli
    fonts:
      - asset: assets/fonts/muli/Muli.ttf
      - asset: assets/fonts/muli/Muli-Bold.ttf
        weight: 700
      - asset: assets/fonts/muli/Muli-Light.ttf
        weight: 300
   
  
